[pytest]
;addopts = -m "not e2e"
markers =
    smoke: 核心冒烟测试
    regression: 完整回归测试
    negative: 异常场景测试
    e2e: 跨系统端到端测试
    slow: 执行时间较长的测试
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(name)s - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
